import Head from "next/head";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export default function AlternativeEducationPage() {
    return (
        <>
            <Head>
                <title>VCIL Community</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Footer />
        </>
    );
}