import Head from "next/head";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import VCILPageLayout from "../../components/VcilCommunity/Layout";

export default function Home() {
    return (
        <>
            <Head>
                <title>VCIL Community</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <VCILPageLayout />
            <Footer />
        </>
    );
}
